=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/animales.dtd
<!ELEMENT zoologico (zona+, animal*, espectaculo?)>
<!ELEMENT zona (#PCDATA | numeroRecintos)*>
<!ELEMENT animal (nombre, especie, ( terrestre | acuatico))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT especie (#PCDATA)>
<!ELEMENT terrestre EMPTY>
<!ELEMENT acuatico EMPTY>
<!ELEMENT espectaculo EMPTY>
<!ELEMENT numeroRecintos (#PCDATA)>
<!ENTITY % attNombre "nombre CDATA #REQUIRED">
<!ATTLIST zoologico %attNombre; 
                    ciudad (Fuengirola | Córdoba | Valencia) "Fuengirola"
                    webVentaEntradas CDATA #FIXED "www.entradas.com"
                    empresaTransporte CDATA #IMPLIED>
<!ATTLIST zona nombre ID #IMPLIED>
<!ATTLIST animal zona IDREF #IMPLIED>
<!ATTLIST espectaculo zonas IDREFS #IMPLIED
                        %attNombre;>
<!ENTITY bioparc "Zoológicos Bioparc S.L.">

=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/animales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zoologico SYSTEM "animales.dtd">
<zoologico nombre="Bioparc" ciudad="Fuengirola" webVentaEntradas="www.entradas.com"
empresaTransporte="Autocares Pérez">
	<zona nombre="desierto">Me encanta porque está nueva, amplía y muy bien cuidada
		<numeroRecintos>10</numeroRecintos>
	</zona>
	<zona nombre="ártico">Corresponde a &bioparc;</zona>
	<animal zona="desierto">
		<nombre>Piquipiqui</nombre>
		<especie>Reina Cobra</especie>
		<terrestre/>
	</animal>
	<espectaculo nombre="aves" zonas="desierto ártico"/>
</zoologico>
