=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/batman.dtd
<!ELEMENT batman (personajes, batalla*, pelicula+)>
<!ELEMENT batalla EMPTY>
<!ELEMENT pelicula EMPTY>
<!ELEMENT personajes (personaje)+>
<!ELEMENT personaje (nombreReal, edad?, (heroe | villano))>
<!ELEMENT nombreReal (#PCDATA)>
<!ELEMENT edad (#PCDATA | fechaNacimiento)*>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT heroe EMPTY>
<!ELEMENT villano EMPTY>
<!ATTLIST batman losMejoresPersonajes IDREFS #REQUIRED>
<!ATTLIST personaje nombre (batman | robin | joker | pingÃ¼ino | Harley) "batman"
                    colorTraje CDATA #IMPLIED
                    altura CDATA #REQUIRED
                    ciudad CDATA #FIXED "Gotham City"
                    codigo ID #REQUIRED
                    codigoDeEnemigoPrincipal IDREF #IMPLIED>
<!ENTITY nolan "Christopher Nolan">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST batalla %atributoNombre;>
<!ATTLIST pelicula %atributoNombre;>

=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/batman.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE batman SYSTEM "batman.dtd">
<batman losMejoresPersonajes="bat har">
	<personajes>
		<personaje nombre="batman" codigo="bat" codigoDeEnemigoPrincipal="jok" colorTraje="Negro" altura="190" ciudad="Gotham City">
			<nombreReal>Bruce Wayne de &nolan;</nombreReal>
			<edad>40
				<fechaNacimiento>3/10/1983</fechaNacimiento>
			</edad>
			<heroe/>
		</personaje>
		<personaje nombre="Harley" codigo="har" altura="180">
			<nombreReal>Doctora psicóloga</nombreReal>
			<edad>32
				<fechaNacimiento>3/10/1991</fechaNacimiento>
			</edad>
			<villano/>
		</personaje>
		<personaje nombre="joker" codigo="jok"  codigoDeEnemigoPrincipal="bat" altura="190">
			<nombreReal>Mafiosillo</nombreReal>
			<edad>57
				<fechaNacimiento>3/10/1966</fechaNacimiento>
			</edad>
			<villano/>
		</personaje>
	</personajes>
	<batalla nombre="Barcos explosivos"/>
	<pelicula nombre="El caballero oscuro"/>
</batman>
