=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/comida-mexicana.dtd
<!ELEMENT restaurante (platos, ofertas)>
<!ELEMENT platos (plato+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT plato (nombre, casero?, precio, (existencias | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT casero EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT existencias EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT oferta (#PCDATA | platoReferido)*>
<!ELEMENT platoReferido ANY>
<!ATTLIST restaurante direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957591456">
<!ATTLIST plato codigo ID #REQUIRED
                ingredientePrincipal (queso | frijoles | chile) "queso">
<!ATTLIST platoReferido codigoPlato IDREF #REQUIRED
                        platoCombinado IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY picante "tres jalapeÃ±os">

=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/DTD/examenes antiguos/2018/comida-mexicana.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "comida-mexicana.dtd">
<restaurante direccion="Calle el taquito" nombre="El tacazo" telefono="957591456">
  <platos>
    <plato codigo="ques" ingredientePrincipal="queso">
      <nombre>Quesadillas</nombre>
      <casero/>
      <precio coste="6" />
      <existencias />
    </plato>
    <plato codigo="ench">
      <nombre>Enchilada &picante;</nombre>
      <precio coste="20" />
      <agotado />
    </plato>
  </platos>
  <ofertas>
    <oferta coste="15">2x1 
      <platoReferido codigoPlato="ques" platoCombinado="ques ench" />
    </oferta>
  </ofertas>
</restaurante>
