=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/XSD/examenes antiguos/alemanes/alemanes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="alemanes" type="tipoAlemanes"/>

  <xs:complexType name="tipoAlemanes" mixed="true">
    <xs:all>
      <xs:element name="familia" type="tipoFamilia"/>
      <xs:element name="lugares" type="tipoLugares"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="tipoFamilia">
    <xs:sequence>
      <xs:element name="miembro" type="tipoMiembro" maxOccurs="unbounded"/>
      <xs:element name="mascota" type="tipoMascota" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="nombre" type="xs:string"/>
    <xs:attribute name="countPersonas" type="xs:integer"/>
  </xs:complexType>

  <xs:simpleType name="tipoNombreMiembro">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Olga"/>
      <xs:enumeration value="Jörg"/>
      <xs:enumeration value="Ursula"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoDni">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}([A-Z]|[a-z])"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoLugares">
    <xs:sequence>
      <xs:element name="lugar" type="tipoLugar" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoLugar">
    <xs:choice>
      <xs:element name="acontecimiento" type="tipoAcontecimiento"/>
      <xs:element name="personasEnLugar" type="tipoPersonasEnLugar"/>
    </xs:choice>
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="tipoPersonasEnLugar">
    <xs:simpleContent>
      <xs:extension base="numericoEntre0y100">
        <xs:attribute name="nacionalidad" type="tipoNacionalidad" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="numericoEntre0y10000">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10000"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="numericoEntre0y100">
    <xs:restriction base="numericoEntre0y10000">
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoAcontecimiento">
    <xs:attribute name="anio" type="numericoEntre0y10000"/>
  </xs:complexType>

  <xs:simpleType name="tipoNacionalidadEuropea">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Española"/>
      <xs:enumeration value="Británica"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoNacionalidadAmericana">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EEUU"/>
      <xs:enumeration value="Peruana"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoNacionalidad">
    <xs:union memberTypes="tipoNacionalidadEuropea tipoNacionalidadAmericana"/>
  </xs:simpleType>

  <xs:simpleType name="tipoNacionalidades">
    <xs:list itemType="tipoNacionalidad"/>
  </xs:simpleType>

  <xs:complexType name="tipoMascota">
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="tipoMiembro">
    <xs:complexContent>
      <xs:extension base="tipoMascota">
        <xs:attribute name="dni" type="tipoDni"/>
        <xs:attribute name="nacionalidades" type="tipoNacionalidades"/>
          </xs:extension>
    </xs:complexContent>
  </xs:complexType>  

</xs:schema>

=== albagar2/LMSGI_2023-24/Unidad_04_DTD_XSD/XSD/examenes antiguos/Desarrollar-XML-y-XSD/alemanes/alemanes.xml
<?xml version="1.0" encoding="UTF-8"?>
<alemanes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="alemanes.xsd">
  Un montón de Alemanes
  <familia nombre="Schawtz" countPersonas="3">
    <miembro nombre="Olga" dni="12345678a"/>
    <miembro nombre="Jörg" nacionalidades="EEUU Peruana Española Británica"/>
    <miembro nombre="Ursula"/>
    <mascota nombre="Princesa"/>
  </familia>
  <lugares>
    <lugar nombre="">
      <acontecimiento anio="2021"></acontecimiento>
    </lugar>
    <lugar nombre="">
      <personasEnLugar nacionalidad="Peruana">14</personasEnLugar>
    </lugar>
  </lugares>
</alemanes>
